//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// EasySFTP.rc で使用
//
#define IDS_APP_TITLE                   101
#define IDD_ABOUTBOX                    103
#define IDS_BYTE                        104
#define IDS_ROOTDIR                     105
#define IDS_TRANSFER_RATE               106
#define IDI_EASYFTP                     107
#define IDS_CONNECTMODE_FTP             107
#define IDS_CONNECTMODE_SFTP            108
#define IDC_EASYFTP                     109
#define IDS_ADDHOST_PROP                109
#define IDS_CHANGEHOST_PROP             110
#define IDS_FOLDER_DIALOG               111
#define IDS_FINISHED                    112
#define IDS_CANCELED                    113
#define IDS_WAITING                     114
#define IDS_NEW_DIRECTORY               116
#define IDS_AUTH_FAILED                 117
#define IDS_UNAVAILABLE                 118
#define IDS_MULTI_SELECT                119
#define IDS_TOTAL                       120
#define IDS_TRANSFER_COUNT              121
#define IDS_ALL_FILTER                  122
#define IDS_SHORTCUT_PREFIX             123
#define IDS_UNKNOWN_SIZE                124
#define IDS_REGISTER_BUTTON             125
#define IDS_UNREGISTER_BUTTON           126
#define IDR_MAINFRAME                   128
#define IDB_TOOLBAR                     134
#define IDD_OPTION                      134
#define IDR_POPUP                       135
#define IDB_ADDRESS_BUTTONS             138
#define IDB_TOOLBAR_L                   144
#define IDB_ADDRESS_BUTTONS_L           145
#define IDS_HEAD_FILE_NAME              201
#define IDS_HEAD_SIZE                   202
#define IDS_HEAD_TYPE                   203
#define IDS_HEAD_MODIFY_TIME            204
#define IDS_HEAD_PERMISSIONS            205
#define IDS_EXTERNAL_APP_IS_DOWNLOADING 301
#define IDS_INVALID_PORT                302
#define IDS_DATA_ON_CLIPBOARD           302
#define IDS_NO_USER_NAME                303
#define IDS_RESTART_APP                 303
#define IDS_REGESFTP_NOT_FOUND          304
#define IDS_PKEY_FILE_NOT_FOUND         305
#define IDS_FAILED_TO_INIT_EASYSFTP_IN_REGHOOK 305
#define IDS_UNABLE_TO_LOAD_PKEY         306
#define IDS_FAILED_TO_INIT_APP          306
#define IDS_FAILED_TO_LOAD_SYSLIBS      307
#define IDS_CANNOT_RUN_IN_EMULATION_MODE 308
#define IDS_FAILED_TO_INIT_SHELLDLL     309
#define IDS_DELETE_CONFIRM              310
#define IDS_DELETE_MULTIPLE             311
#define IDS_NEW_FINGER_PRINT            316
#define IDS_FINGER_PRINT_MISMATCH       317
#define IDS_INVALID_FILE_NAME_CHAR      320
#define IDS_TYPE_NONE                   401
#define IDS_TYPE_TEXT                   402
#define IDS_TYPE_BINARY                 403
#define IDS_TYPE_DIRECTORY              404
#define IDS_TYPE_MIXED                  405
#define IDC_REGISTER                    1051
#define IDC_REGISTER_SYSTEM             1052
#define IDC_FEATURES                    1053
#define IDC_LINK_TO_REPOSITORY          1054
#define IDC_VERSION                     1055
#define IDS_UNKNOWN_HOST                10001
#define IDS_FAILED_TO_CONNECT           10002
#define IDS_DIRCHANGE_FAILED            11001
#define IDS_DIRLIST_RECEIVED            11002
#define IDS_CANNOT_CREATE_DIRECTORY     11003
#define IDS_CONNECTING                  15001
#define IDS_AUTHENTICATING              15002
#define IDS_CONNECTED                   15003
#define IDS_COMMAND_OK                  15004
#define IDS_COMMAND_FAILED              15005
#define ID_STATUS_HOST                  20001
#define ID_STATUS_SECURE                20002
#define ID_STATUS_TEXT                  20003
#define ID_FILE_CONNECT                 0xA001
#define ID_FILE_DISCONNECT              0xA002
#define ID_FILE_QUICK_CONNECT           0xA003
#define ID_FILE_OPEN                    0xA004
#define ID_FILE_SAVE_AS                 0xA005
#define ID_FILE_RENAME                  0xA006
#define ID_FILE_NEW_FOLDER              0xA007
#define ID_FILE_EXIT                    0xA008
#define ID_FILE_PROPERTY                0xA009
#define ID_FILE_CREATE_SHORTCUT         0xA00A
#define ID_EDIT_DELETE                  0xA101
#define ID_EDIT_UPLOAD                  0xA102
#define ID_EDIT_DOWNLOAD                0xA103
#define ID_EDIT_UPLOAD_ALL              0xA104
#define ID_EDIT_DOWNLOAD_ALL            0xA105
#define ID_EDIT_CUT                     0xA106
#define ID_EDIT_COPY                    0xA107
#define ID_EDIT_PASTE                   0xA108
#define ID_EDIT_SELECT_ALL              0xA109
#define ID_EDIT_INVERT_SELECTION        0xA10A
#define ID_VIEW_TRANSFER                0xA201
#define ID_VIEW_REFRESH                 0xA202
#define ID_VIEW_GO_FOLDER               0xA203
#define ID_VIEW_PARENT_FOLDER           0xA204
#define ID_VIEW_SERVER_GO_FOLDER        0xA205
#define ID_VIEW_SERVER_PARENT_FOLDER    0xA206
#define ID_TRANSFER_MODE_AUTO           0xA301
#define ID_TRANSFER_MODE_TEXT           0xA302
#define ID_TRANSFER_MODE_BINARY         0xA303
#define ID_TRANSFER_LOCAL_MODE          0xA304
#define ID_TRANSFER_LOCAL_CRLF          0xA305
#define ID_RETURN_MODE_CRLF             0xA305
#define ID_TRANSFER_LOCAL_CR            0xA306
#define ID_RETURN_MODE_CR               0xA306
#define ID_TRANSFER_LOCAL_LF            0xA307
#define ID_RETURN_MODE_LF               0xA307
#define ID_TRANSFER_SERVER_MODE         0xA308
#define ID_TRANSFER_SERVER_CRLF         0xA309
#define ID_TRANSFER_SERVER_CR           0xA30A
#define ID_TRANSFER_SERVER_LF           0xA30B
#define ID_TRANSFER_OPEN_LOCAL          0xA351
#define ID_TRANSFER_CANCEL              0xA352
#define ID_TOOL_OPTION                  0xA401
#define ID_HELP_ABOUT                   0xA501
#define ID_DROP_MOVE                    0xAD01
#define ID_DROP_COPY                    0xAD02
#define ID_DROP_LINK                    0xAD03
#define ID_DROP_CANCEL                  0xAD04
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        146
#define _APS_NEXT_COMMAND_VALUE         32870
#define _APS_NEXT_CONTROL_VALUE         1056
#define _APS_NEXT_SYMED_VALUE           117
#endif
#endif
