//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// ShellDLL.rc で使用
//
#define IDI_EASYFTP                     101
#define IDI_NETDRIVE                    102
#define IDR_SHELLMENU                   102
#define IDS_APP_TITLE                   103
#define IDD_MULTIPLE_ERROR              103
#define IDS_BYTE                        104
#define IDI_ICON1                       104
#define IDI_NEWHOST                     104
#define IDD_PROP_HOST                   106
#define IDS_TRANSFER_RATE               106
#define IDS_CONNECTMODE_FTP             107
#define IDS_CONNECTMODE_SFTP            108
#define IDS_ADDHOST_PROP                109
#define IDS_CHANGEHOST_PROP             110
#define IDS_FOLDER_DIALOG               111
#define IDS_FINISHED                    112
#define IDS_CANCELED                    113
#define IDS_WAITING                     114
#define IDS_AUTH_FAILED                 117
#define IDS_UNAVAILABLE                 118
#define IDS_MULTI_SELECT                119
#define IDS_TOTAL                       120
#define IDS_TRANSFER_COUNT              121
#define IDS_ALL_FILTER                  122
#define IDS_SHORTCUT_PREFIX             123
#define IDS_UNKNOWN_SIZE                124
#define IDS_SERVER_HOST                 125
#define IDS_SERVER_ADDRESS              126
#define IDS_FTP_WELCOME                 127
#define IDS_SSH_VERSION                 128
#define IDD_QUICK_CONNECT               129
#define IDS_SFTP_VERSION                129
#define IDS_SERVER_NAME                 130
#define IDD_TRANSFER                    131
#define IDS_SSH_KEY_TYPE                131
#define IDD_PROP_CHARSET                132
#define IDS_SSH_KEX                     132
#define IDD_PROP_TRANSFER               134
#define IDR_POPUP                       135
#define IDD_FILENAME                    136
#define IDD_PASSWORD                    139
#define IDD_SFILE_PROPERTY              140
#define IDD_NEWLINK                     141
#define IDD_SERVER_INFO                 142
#define IDS_NOT_CONNECTED               151
#define IDS_CONNECTED                   152
#define IDS_HEAD_NAME                   201
#define IDS_HEAD_FILE_NAME              202
#define IDS_HEAD_FILE_EXT               203
#define IDS_HEAD_SIZE                   204
#define IDS_HEAD_TYPE                   205
#define IDS_HEAD_PERMISSIONS            206
#define IDS_HEAD_CREATE_TIME            207
#define IDS_HEAD_MODIFY_TIME            208
#define IDS_HEAD_TRANSFER_TYPE          209
#define IDS_HEAD_UID                    210
#define IDS_HEAD_GID                    211
#define IDS_RHEAD_NAME                  251
#define IDS_RHEAD_MODE                  252
#define IDS_RHEAD_HOST                  253
#define IDS_RHEAD_PORT                  254
#define IDS_RHEAD_STATUS                255
#define IDS_NO_HOST_NAME                301
#define IDS_INVALID_PORT                302
#define IDS_NO_USER_NAME                303
#define IDS_NO_PKEY_FILE_NAME           304
#define IDS_PKEY_FILE_NOT_FOUND         305
#define IDS_UNABLE_TO_LOAD_PKEY         306
#define IDS_NO_PASSWORD                 307
#define IDS_NO_SET_NAME                 309
#define IDS_NO_OWNER                    312
#define IDS_NO_OWNER_ID                 313
#define IDS_NO_GROUP                    314
#define IDS_NO_GROUP_ID                 315
#define IDS_NEW_FINGER_PRINT            316
#define IDS_FINGER_PRINT_MISMATCH       317
#define IDS_NO_LINK_TO                  318
#define IDS_NO_FILE_NAME                319
#define IDS_INVALID_FILE_NAME_CHAR      320
#define IDS_DELETE_HOST                 322
#define IDS_DELETE_FILE                 323
#define IDS_DELETE_DIRECTORY            324
#define IDS_DELETE_MULTIPLE             325
#define IDS_PAGEANT_NOT_AVAILABLE       326
#define IDS_WINSSHAGENT_NOT_AVAILABLE   327
#define IDS_TYPE_NONE                   401
#define IDS_TYPE_TEXT                   402
#define IDS_TYPE_BINARY                 403
#define IDS_TYPE_DIRECTORY              404
#define IDC_HOST_NAME                   1000
#define IDC_USER_NAME                   1001
#define IDC_MSG_ICON                    1001
#define IDC_PASSWORD                    1002
#define IDC_PORT                        1003
#define IDC_ERROR_LIST                  1003
#define IDC_USE_SFTP                    1004
#define IDC_INFO                        1004
#define IDC_USE_THUMBNAIL               1005
#define IDC_PKEY_FILE                   1006
#define IDC_PKEY_SEARCH                 1007
#define IDC_FILE_LIST                   1008
#define IDC_NAME                        1009
#define IDC_DEF_PORT                    1012
#define IDC_CONNECT_MODE                1013
#define IDC_LOCAL_CRLF                  1015
#define IDC_LOCAL_PATH                  1016
#define IDC_LOCAL_CR                    1016
#define IDC_ADD_FILE                    1017
#define IDC_LOCAL_PATH_SEARCH           1017
#define IDC_LOCAL_LF                    1017
#define IDC_DEL_FILE                    1018
#define IDC_SERVER_PATH                 1018
#define IDC_SERVER_CRLF                 1018
#define IDC_SERVER_CR                   1019
#define IDC_SERVER_LF                   1020
#define IDC_SERVER_FILE_CHARSET         1021
#define IDC_FILE_AUTO                   1023
#define IDC_FILE_TEXT                   1024
#define IDC_FILE_BINARY                 1025
#define IDC_TEXTFILE_PATTERN            1026
#define IDC_ADD_SYSTEM                  1027
#define IDC_KEEP_RECV_MODIFY_TIME       1028
#define IDC_KEEP_SEND_MODIFY_TIME       1029
#define IDC_FILE_NAME                   1029
#define IDC_MESSAGE                     1030
#define IDC_DIRECTORY                   1030
#define IDC_LINK_NAME                   1030
#define IDC_FILE_SIZE                   1031
#define IDC_CREATION_TIME               1032
#define IDC_MODIFY_TIME                 1033
#define IDC_AUTH_PASSWORD               1034
#define IDC_AUTH_PKEY                   1035
#define IDC_AUTH_PAGEANT                1036
#define IDC_USER_READ                   1037
#define IDC_AUTH_WIN_SSHAGENT           1037
#define IDC_USER_WRITE                  1038
#define IDC_USER_EXECUTE                1039
#define IDC_GROUP_READ                  1040
#define IDC_GROUP_WRITE                 1041
#define IDC_GROUP_EXECUTE               1042
#define IDC_OTHER_READ                  1043
#define IDC_OTHER_WRITE                 1044
#define IDC_OTHER_EXECUTE               1045
#define IDC_OWNER                       1046
#define IDC_GROUP                       1047
#define IDC_CUR_DIR                     1048
#define IDC_HARD_LINK                   1049
#define ID_RCOMMAND_ADD_HOST            6001
#define IDS_UNKNOWN_HOST                10001
#define IDS_FAILED_TO_CONNECT           10002
#define IDS_FAILED_TO_CONNECT_BANNED    10003
#define IDS_FAILED_TO_CONNECT_MSG       10004
#define IDS_COMMAND_OK                  15004
#define IDS_COMMAND_FAILED              15005
#define IDS_COMMAND_UNKNOWN_ERROR       15006
#define IDS_COMMAND_OUTOFMEMORY         15007
#define IDS_COMMAND_CONNECTION_ERROR    15008
#define IDS_SFTP_UNKNOWN                17000
#define IDS_SFTP_EOF                    17001
#define IDS_SFTP_NO_SUCH_FILE           17002
#define IDS_SFTP_PERMISSION_DENIED      17003
#define IDS_SFTP_FAILURE                17004
#define IDS_SFTP_BAD_MESSAGE            17005
#define IDS_SFTP_NO_CONNECTION          17006
#define IDS_SFTP_CONNECTION_LOST        17007
#define IDS_SFTP_OP_UNSUPPORTED         17008
#define IDS_SFTP_INVALID_HANDLE         17009
#define IDS_SFTP_NO_SUCH_PATH           17010
#define IDS_SFTP_FILE_ALREADY_EXISTS    17011
#define IDS_SFTP_WRITE_PROTECT          17012
#define IDS_SFTP_NO_MEDIA               17013
#define IDS_SFTP_NO_SPACE_ON_FILESYSTEM 17014
#define IDS_SFTP_QUOTA_EXCEEDED         17015
#define IDS_SFTP_UNKNOWN_PRINCIPAL      17016
#define IDS_SFTP_LOCK_CONFLICT          17017
#define IDS_SFTP_DIR_NOT_EMPTY          17018
#define IDS_SFTP_NOT_A_DIRECTORY        17019
#define IDS_SFTP_INVALID_FILENAME       17020
#define IDS_SFTP_LINK_LOOP              17021
#define IDS_SFTP_CANNOT_DELETE          17022
#define IDS_SFTP_INVALID_PARAMETER      17023
#define IDS_SFTP_FILE_IS_A_DIRECTORY    17024
#define IDS_SFTP_BYTE_RANGE_LOCK_CONFLICT 17025
#define IDS_SFTP_BYTE_RANGE_LOCK_REFUSED 17026
#define IDS_SFTP_DELETE_PENDING         17027
#define IDS_SFTP_FILE_CORRUPT           17028
#define IDS_SFTP_OWNER_INVALID          17029
#define IDS_SFTP_GROUP_INVALID          17030
#define IDS_SFTP_NO_MATCHING_BYTE_RANGE_LOCK 17031
#define ID_FILE_OPEN                    21004
#define ID_FILE_SAVE_AS                 21005
#define ID_FILE_RENAME                  21006
#define ID_FILE_NEW_FOLDER              21007
#define ID_FILE_PROPERTY                21009
#define ID_EDIT_DELETE                  22001
#define ID_VIEW_REFRESH                 23002
#define ID_RETURN_MODE_CRLF             24005
#define ID_RETURN_MODE_CR               24006
#define ID_RETURN_MODE_LF               24007
#define ID_TRANSFER_OPEN_LOCAL          24501
#define ID_TRANSFER_CANCEL              24502
#define ID_FILE_CREATE_SHORTCUT         32838
#define ID_EDIT_CUT                     32841
#define ID_EDIT_COPY                    32843
#define ID_EDIT_PASTE                   32845
#define ID_LISTVIEWSERVERDROP_32852     32852
#define ID_LISTVIEWSERVERDROP_32853     32853
#define ID_LISTVIEWSERVERDROP_32854     32854
#define ID_LISTVIEWSERVERDROP_32855     32855
#define ID_DROP_MOVE                    32856
#define ID_DROP_COPY                    32857
#define ID_DROP_LINK                    32858
#define ID_DROP_CANCEL                  32859
#define ID_HOST_BASE                    40001
#define ID_HOST_CONNECT                 40001
#define ID_HOST_RENAME                  40002
#define ID_HOST_DELETE                  40003
#define ID_HOST_PROPERTY                40004
#define ID_ITEM_BASE                    41001
#define ID_ITEM_OPEN                    41001
#define ID_ITEM_EXPLORE                 41002
#define ID_ITEM_OPEN_AS_TEXT            41003
#define ID_PARENT_PROPERTIES            41003
#define ID_ITEM_CUT                     41004
#define ID_ITEM_COPY                    41005
#define ID_ITEM_DELETE                  41007
#define ID_ITEM_RENAME                  41008
#define ID_ITEM_PROPERTY                41009
#define ID_PARENT_BASE                  41101
#define ID_PARENT_NEW_FOLDER            41101
#define ID_PARENT_NEW_SHORTCUT          41102
#define ID_PARENT_PROPERTY              41103
#define ID_ROOT_SERVER_INFO             41201
#define ID_ROOT_IDBASE                  41201

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        107
#define _APS_NEXT_COMMAND_VALUE         41018
#define _APS_NEXT_CONTROL_VALUE         1006
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
